/*
 * Created on 2025-10-13 ( 13:34:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.rest.services;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

import exforthia.embercrypt.persistence.entities.VaultPassword;
import exforthia.embercrypt.persistence.repositories.VaultPasswordRepository;
import exforthia.embercrypt.rest.dto.holder.VaultPasswordHolder;
import exforthia.embercrypt.rest.dto.sender.VaultPasswordSender;
import exforthia.embercrypt.rest.services.commons.GenericService;
import exforthia.embercrypt.funct.mappers.VaultPasswordMappr;

/**
 * REST service for entity "VaultPassword" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class VaultPasswordService extends GenericService<VaultPassword, VaultPasswordHolder, VaultPasswordSender> {

	private static final Logger logger = LoggerFactory.getLogger(VaultPasswordService.class);

	@Autowired
	private VaultPasswordRepository repository;

	@Autowired
	private VaultPasswordMappr mapper;
	
	/**
	 * Converts a collection of JPA ENTITIES to a collection of Holders
	 * 
	 * @param entities
	 * @return
	 */
	@Override
	protected List<VaultPasswordHolder> entityListToHolderList(Iterable<VaultPassword> entities) {
		List<VaultPasswordHolder> holderList = new ArrayList<>();
		if (entities != null) {
			for (VaultPassword entity : entities) {
				holderList.add(mapper.entityToHolder(entity));
			}
		}
		return holderList;
	}
	private Long getEntityIdFromHolder(VaultPasswordHolder holder) {
		return holder.getIdPassword();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<VaultPasswordHolder> findAll() {
		logger.debug("findAll()");
		Iterable<VaultPassword> all = repository.findAll();
		return entityListToHolderList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param idPassword 
	 * @return the entity or null if not found
	 */
	public VaultPasswordHolder findById(long idPassword) {
		Long entityId = idPassword;
		logger.debug("findById({})", entityId);
		Optional<VaultPassword> optionalEntity = repository.findById(entityId);
		return optionalEntity.map(mapper::entityToHolder).orElse(null);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param idPassword 
	 * @param sender 
	 */
	public void save(long idPassword, VaultPasswordSender sender) {
		Long entityId = idPassword;
		logger.debug("save({},{})", entityId, sender);
		// Convert sender to entity and save
		VaultPassword entity = mapper.senderToEntity(sender);
		// force PK in entity (just to be sure to conform with the given PK) 
		entity.setIdPassword(idPassword);
		repository.save(entity);
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param holder
	 * @return true if updated, false if not found
	 */
	public boolean update(VaultPasswordHolder holder) {
		logger.debug("update({})", holder);
		if (repository.existsById(getEntityIdFromHolder(holder))) {
			// For full update, we can map directly from holder to entity
			VaultPassword entity = mapper.holderToEntity(holder);
			repository.save(entity);
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param idPassword 
	 * @param sender
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(long idPassword, VaultPasswordSender sender) {
		Long entityId = idPassword;
		logger.debug("partialUpdate({}, {})", entityId, sender);
		Optional<VaultPassword> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			VaultPassword entity = optionalEntity.get();
			// Update entity with sender data (only non-null fields from sender)
			mapper.senderToEntity(sender, entity);
			repository.save(entity);
			return true; // found and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param sender
	 * @return true if created, false if already exists
	 */
	public boolean create(VaultPasswordSender sender) {
		logger.debug("create({})", sender);
		// auto-generated Primary Key
		VaultPassword entity = mapper.senderToEntity(sender);
		repository.save(entity);
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param idPassword 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(long idPassword) {
		Long entityId = idPassword;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<VaultPasswordHolder> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<VaultPassword> list = repository.findByTitle(title);
		List<VaultPassword> list = repository.findByTitleContaining(title);
		return entityListToHolderList(list);
	}

	public List<VaultPasswordHolder> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<VaultPassword> list = repository.findByTitle(title);
		List<VaultPassword> list = repository.findByPrice(price);
		return entityListToHolderList(list);
	}

	public List<VaultPasswordHolder> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<VaultPassword> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToHolderList(list);
	}
***/
}
