/*
 * Created on 2025-09-29 ( 11:35:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package exforthia.embercrypt.rest.services;

import java.util.List;
import java.util.Optional;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import exforthia.embercrypt.persistence.entities.VaultPassword;
import exforthia.embercrypt.persistence.repositories.VaultPasswordRepository;
import exforthia.embercrypt.rest.dto.VaultPasswordDTO;
import exforthia.embercrypt.rest.services.commons.GenericService;

/**
 * REST service for entity "VaultPassword" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class VaultPasswordService extends GenericService<VaultPassword, VaultPasswordDTO> {

	private static final Logger logger = LoggerFactory.getLogger(VaultPasswordService.class);

	@Autowired
	private VaultPasswordRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public VaultPasswordService(VaultPasswordRepository repository) {
		super(VaultPassword.class, VaultPasswordDTO.class);
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Long getEntityId(VaultPasswordDTO dto) {
		return dto.getIdPassword();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<VaultPasswordDTO> findAll() {
		logger.debug("findAll()");
		Iterable<VaultPassword> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param idPassword 
	 * @return the entity or null if not found
	 */
	public VaultPasswordDTO findById(long idPassword) {
		Long entityId = idPassword;
		logger.debug("findById({})", entityId);
		Optional<VaultPassword> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param idPassword 
	 * @param dto 
	 */
	public void save(long idPassword, VaultPasswordDTO dto) {
		Long entityId = idPassword;
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setIdPassword(idPassword);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(VaultPasswordDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param idPassword 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(long idPassword, VaultPasswordDTO dto) {
		Long entityId = idPassword;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<VaultPassword> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			VaultPassword entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(VaultPasswordDTO dto) {
		logger.debug("create({})", dto);
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param idPassword 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(long idPassword) {
		Long entityId = idPassword;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<VaultPasswordDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<VaultPassword> list = repository.findByTitle(title);
		List<VaultPassword> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<VaultPasswordDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<VaultPassword> list = repository.findByTitle(title);
		List<VaultPassword> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<VaultPasswordDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<VaultPassword> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}
