/*
 * Created on 2025-09-29 ( 11:35:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package exforthia.embercrypt.rest.services;

import java.util.List;
import java.util.Optional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import exforthia.embercrypt.persistence.entities.VaultOtp;
import exforthia.embercrypt.persistence.repositories.VaultOtpRepository;
import exforthia.embercrypt.rest.dto.VaultOtpDTO;
import exforthia.embercrypt.rest.services.commons.GenericService;

/**
 * REST service for entity "VaultOtp" <br>
 * 
 * This service provides all the necessary operations required by the REST controller <br>
 * 
 * @author Telosys
 *
 */
@Service
public class VaultOtpService extends GenericService<VaultOtp, VaultOtpDTO> {

	private static final Logger logger = LoggerFactory.getLogger(VaultOtpService.class);

	@Autowired
	private VaultOtpRepository repository; // injected by constructor

	/**
	 * Constructor (usable for Dependency Injection)
	 * 
	 * @param repository the repository to be injected
	 */
	public VaultOtpService(VaultOtpRepository repository) {
		super(VaultOtp.class, VaultOtpDTO.class);
	}
	
	/**
	 * Returns the entity ID object from the given DTO
	 *
	 * @param dto
	 * @return
	 */
	private Long getEntityId(VaultOtpDTO dto) {
		return dto.getIdOtp();
	}

	/**
	 * Finds all occurrences of the entity
	 *
	 * @return
	 */
	public List<VaultOtpDTO> findAll() {
		logger.debug("findAll()");
		Iterable<VaultOtp> all = repository.findAll();
		return entityListToDtoList(all);
	}

	/**
	 * Finds the entity identified by the given PK
	 *
	 * @param idOtp 
	 * @return the entity or null if not found
	 */
	public VaultOtpDTO findById(long idOtp) {
		Long entityId = idOtp;
		logger.debug("findById({})", entityId);
		Optional<VaultOtp> optionalEntity = repository.findById(entityId);
		return entityToDto(optionalEntity);
	}

	/**
	 * Saves the given entity with the given PK <br>
	 * "UPSERT" operation (updated if it exists or created if it does not exist)
	 *
	 * @param idOtp 
	 * @param dto 
	 */
	public void save(long idOtp, VaultOtpDTO dto) {
		Long entityId = idOtp;
		logger.debug("save({},{})", entityId, dto);
		// force PK in DTO (just to be sure to conform with the given PK) 
		dto.setIdOtp(idOtp);
		repository.save(dtoToEntity(dto));
	}

	/**
	 * Updates the given entity if it exists
	 *
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean update(VaultOtpDTO dto) {
		logger.debug("update({})", dto);
		if (repository.existsById(getEntityId(dto))) {
			repository.save(dtoToEntity(dto));
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Updates partially the given entity if it exists
	 *
	 * @param idOtp 
	 * @param dto
	 * @return true if updated, false if not found
	 */
	public boolean partialUpdate(long idOtp, VaultOtpDTO dto) {
		Long entityId = idOtp;
		logger.debug("partialUpdate({}, {})", entityId, dto);
		Optional<VaultOtp> optionalEntity = repository.findById(entityId);
		if (optionalEntity.isPresent()) {
			VaultOtp entity = optionalEntity.get();
			// implement here the partial update
			// entity.setXxx(dto.getXxx());
			// etc ...
			repository.save(entity);
			return true; // find and updated
		} else {
			return false; // not found (not updated)
		}
	}

	/**
	 * Creates the given entity
	 *
	 * @param dto
	 * @return true if created, false if already exists
	 */
	public boolean create(VaultOtpDTO dto) {
		logger.debug("create({})", dto);
		// auto-generated Primary Key
		repository.save(dtoToEntity(dto));
		return true; // always created
	}

	/**
	 * Deletes an entity by its PK
	 *
	 * @param idOtp 
	 * @return true if deleted, false if not found
	 */
	public boolean deleteById(long idOtp) {
		Long entityId = idOtp;
		logger.debug("deleteById({})", entityId);
		if (repository.existsById(entityId)) {
			repository.deleteById(entityId);
			return true; // find and deleted
		} else {
			return false; // not found (not deleted)
		}
	}

	// -----------------------------------------------------------------------------------------
	// Specific "finders"
	// -----------------------------------------------------------------------------------------
/***
	public List<VaultOtpDTO> findByTitle(String title) {
		logger.debug("findByTitle({})", title);
		// List<VaultOtp> list = repository.findByTitle(title);
		List<VaultOtp> list = repository.findByTitleContaining(title);
		return entityListToDtoList(list);
	}

	public List<VaultOtpDTO> findByPrice(BigDecimal price) {
		logger.debug("findByPrice({})", price);
		// List<VaultOtp> list = repository.findByTitle(title);
		List<VaultOtp> list = repository.findByPrice(price);
		return entityListToDtoList(list);
	}

	public List<VaultOtpDTO> findByTitleAndPrice(String title, BigDecimal price) {
		logger.debug("findByTitleAndPrice({}, {})", title, price);
		List<VaultOtp> list = repository.findByTitleContainingAndPrice(title, price);
		return entityListToDtoList(list);
	}
***/
}
