/*
 * Created on 2025-10-14 ( 08:56:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.rest.services.commons;

import java.util.List;

/**
 * Abstract class for REST services <br>
 * Uses MapStruct for mapping operations
 * 
 * @author Telosys
 *
 * @param <ENTITY>
 * @param <HOLDER>
 * @param <SENDER>
 */
public abstract class GenericService<ENTITY, HOLDER, SENDER> {

	// MapStruct mapper will be injected in concrete services

	// MapStruct mapper will be injected in concrete services

	/**
	 * Converts a collection of JPA ENTITIES to a collection of Holders
	 * To be implemented by concrete services using their specific mapper
	 * 
	 * @param entities
	 * @return
	 */
	protected abstract List<HOLDER> entityListToHolderList(Iterable<ENTITY> entities);
}