/*
 * Created on 2025-10-13 ( 13:34:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.rest.dto.holder;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * Holder class for "VaultPassword" - Contains ALL entity attributes
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class VaultPasswordHolder implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private long idPassword ;
    //--- OTHER DATA FIELDS 
    private String vaultRef ;
    private byte[] encryptedValue ;
    private LocalDateTime createdAt ;

}