/*
 * Created on 2025-10-14 ( 08:56:31 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.rest.dto.holder;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * Holder class for "VaultOtp" - Contains ALL entity attributes
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class VaultOtpHolder implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private long idOtp ;
    //--- OTHER DATA FIELDS 
    private String vaultRef ;
    private String type ;
    private String label ;
    private Long issuerId ;
    private byte[] secretEncrypted ;
    private String algorithm ;
    private Integer digits ;
    private Integer period ;
    private LocalDateTime createdAt ;

}