/*
 * Created on 2025-10-13 ( 13:34:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.funct.mappers;

import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.Mappings;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.Mapping;

import exforthia.embercrypt.persistence.entities.VaultPassword;
import exforthia.embercrypt.rest.dto.holder.VaultPasswordHolder;
import exforthia.embercrypt.rest.dto.sender.VaultPasswordSender;

/**
 * MapStruct mapper for "VaultPassword" entity
 * 
 * This mapper handles conversions between Entity, Holder, and Sender
 * MapStruct generates the implementation automatically at compile time
 * 
 * @author Telosys
 */
@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface VaultPasswordMappr {

    /**
     * Converts Entity to Holder (for GET responses)
     * 
     * @param entity the JPA entity
     * @return the holder with all data
     */
    VaultPasswordHolder entityToHolder(VaultPassword entity);

    /**
     * Converts Sender to Entity (for POST/PUT requests)
     * 
     * @param sender the sender with user input data
     * @return the JPA entity
     */
    @Mappings({
            @Mapping(target = "idPassword", ignore = true),
            @Mapping(target = "createdAt", ignore = true)
    })
    VaultPassword senderToEntity(VaultPasswordSender sender);

    /**
     * Converts Sender to Entity (for PATCH requests)
     * 
     * @param sender the sender with partial data
     * @param entity the existing entity to update
     */
    @Mappings({
            @Mapping(target = "idPassword", ignore = true),
            @Mapping(target = "createdAt", ignore = true)
    })
    void senderToEntity(VaultPasswordSender sender, @MappingTarget VaultPassword entity);

    /**
     * Converts Holder to Entity (for full updates)
     * 
     * @param holder the holder with complete data
     * @return the JPA entity
     */
    VaultPassword holderToEntity(VaultPasswordHolder holder);
}