/*
 * Created on 2025-09-29 ( 11:35:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package exforthia.embercrypt.rest.dto;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "VaultPassword"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class VaultPasswordDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private long idPassword ;
    //--- OTHER DATA FIELDS 
    private String vaultRef ;
    private byte[] encryptedValue ;
    private LocalDateTime createdAt ;

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VaultPassword[");
		sb.append("idPassword=").append(idPassword);
		sb.append(separator).append("vaultRef=").append(vaultRef);
		// attribute 'encryptedValue' (type byte[]) not usable in toString() 
		sb.append(separator).append("createdAt=").append(createdAt);
		sb.append("]");
		return sb.toString();
	}
}
