/*
 * Created on 2025-09-29 ( 11:35:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package exforthia.embercrypt.rest.dto;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO class for "VaultOtp"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class VaultOtpDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    private long idOtp ;
    //--- OTHER DATA FIELDS 
    private String vaultRef ;
    private String type ;
    private String label ;
    private Long issuerId ;
    private byte[] secretEncrypted ;
    private String algorithm ;
    private Integer digits ;
    private Integer period ;
    private LocalDateTime createdAt ;

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VaultOtp[");
		sb.append("idOtp=").append(idOtp);
		sb.append(separator).append("vaultRef=").append(vaultRef);
		sb.append(separator).append("type=").append(type);
		sb.append(separator).append("label=").append(label);
		sb.append(separator).append("issuerId=").append(issuerId);
		// attribute 'secretEncrypted' (type byte[]) not usable in toString() 
		sb.append(separator).append("algorithm=").append(algorithm);
		sb.append(separator).append("digits=").append(digits);
		sb.append(separator).append("period=").append(period);
		sb.append(separator).append("createdAt=").append(createdAt);
		sb.append("]");
		return sb.toString();
	}
}
