/*
 * Created on 2025-10-14 ( 08:56:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.rest.dto.sender;

import java.io.Serializable;
import java.time.LocalDateTime;

import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Builder;

/**
 * Sender class for "VaultOtp" - Contains only user-input attributes
 * Excludes auto-generated fields and complex objects
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class VaultOtpSender implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY (only non-auto-generated)
    //--- OTHER DATA FIELDS (only non-auto-generated and primitive types)
    private String vaultRef;
    private String type;
    private String label;
    private Long issuerId;
    private byte[] secretEncrypted;
    private String algorithm;
    private Integer digits;
    private Integer period;
    private LocalDateTime createdAt;
}