/*
 * Created on 2025-10-14 ( 08:56:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.rest.controllers;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import exforthia.embercrypt.rest.dto.holder.VaultPasswordHolder;
import exforthia.embercrypt.rest.dto.sender.VaultPasswordSender;
import exforthia.embercrypt.rest.services.VaultPasswordService;

@RestController
@RequestMapping(value = "/api/v1/vaultpassword", produces = MediaType.APPLICATION_JSON_VALUE)
public class VaultPasswordRestController {

	private static final Logger logger = LoggerFactory.getLogger(VaultPasswordRestController.class);
	
	@Autowired
	private VaultPasswordService service;
    
	/**
	 * Get ALL
	 *
	 * @return
	 */
	@GetMapping("")
	protected ResponseEntity<List<VaultPasswordHolder>> findAll() {
    	logger.debug("REST : GET - findAll");
    	List<VaultPasswordHolder> list = service.findAll();
    	return ResponseEntity.ok(list); // always 200
    }
    
    /**
     * Get ONE identified by the given PK
	 *
	 * @param idPassword
     * @return 200 or 404 
     */
    @GetMapping("/{idPassword}")
    protected ResponseEntity<VaultPasswordHolder> findById(@PathVariable long idPassword) {
    	logger.debug("REST : GET - findById");
    	VaultPasswordHolder vaultPasswordHolder = service.findById(idPassword);
		if ( vaultPasswordHolder != null ) {
			return ResponseEntity.ok(vaultPasswordHolder); // 200 OK, found
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found
		}		
    }

    
	/**
 	 * Create if doesn't exist 
	 *
	 * @param vaultPasswordSender
	 * @return 201 created or 409 conflict
	 */
	@PostMapping("")
	protected ResponseEntity<Void> create(@RequestBody VaultPasswordSender vaultPasswordSender) {
    	logger.debug("REST : POST - create");
		if ( service.create(vaultPasswordSender) ) {
			return ResponseEntity.status(HttpStatus.CREATED).build(); // 201 created
		}
		else {
			return ResponseEntity.status(HttpStatus.CONFLICT).build(); // 409 Conflict
		}
	}

	/**
	 * Update or create
	 *
	 * @param idPassword
	 * @param vaultPasswordSender
	 * @return 200 updated or created
	 */
	@PutMapping("/{idPassword}")
	protected ResponseEntity<Void> save(@PathVariable long idPassword, @RequestBody VaultPasswordSender vaultPasswordSender) {
    	logger.debug("REST : PUT - save");
		service.save(idPassword, vaultPasswordSender);
		return ResponseEntity.ok().build(); // OK, updated or created
	}

	/**
 	 * Update if exists 
	 *
	 * @param vaultPasswordHolder
	 * @return 200 updated or 404 not found
	 */
	@PutMapping("")
	protected ResponseEntity<Void> update(@RequestBody VaultPasswordHolder vaultPasswordHolder) {
    	logger.debug("REST : PUT - update");
		if ( service.update(vaultPasswordHolder) ) {
			return ResponseEntity.ok().build(); // 200 OK, found and updated
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
		}
	}

	/**
 	 * Partial update for the given PK (if it exists )
	 *
	 * @param idPassword
	 * @param vaultPasswordSender
	 * @return 200 updated or 404 not found
	 */
	@PatchMapping("/{idPassword}")
	protected ResponseEntity<Void> partialUpdate(@PathVariable long idPassword, @RequestBody VaultPasswordSender vaultPasswordSender) {
    	logger.debug("REST : PATCH - partialUpdate");
    	if ( service.partialUpdate(idPassword, vaultPasswordSender) ) {
    		return ResponseEntity.ok().build(); // OK, found and updated
    	}
    	else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not updated"
    	}
	}

	/**
	 * Delete by PK 
	 *
	 * @param idPassword
	 * @return 204 deleted or 404 not found
	 */
	@DeleteMapping("/{idPassword}")
	protected ResponseEntity<Void> deleteById(@PathVariable long idPassword) {
    	logger.debug("REST : DELETE - deleteById");
		if ( service.deleteById(idPassword) ) {
			return ResponseEntity.noContent().build(); // 204 No content = "deleted"
		}
		else {
			return ResponseEntity.notFound().build(); // 404 Not found = "not deleted"
		}
	}

}
