/*
 * Created on 2025-10-13 ( 13:34:58 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import exforthia.embercrypt.persistence.entities.VaultOtp;

/**
 * Spring Data JPA repository for entity "VaultOtp" <br> 
 * 
 * This repository extends JpaRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
@Repository
public interface VaultOtpRepository extends JpaRepository<VaultOtp, Long> {

	// Insert specific finders here 

	//List<VaultOtp> findByXxx(String xxx);

	//List<VaultOtp> findByXxxStartingWith(String xxx);

	//List<VaultOtp> findByXxxContaining(String xxx);

	//List<VaultOtp> findByYyy(BigDecimal yyy);

	//List<VaultOtp> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
