/*
 * Created on 2025-10-14 ( 08:56:32 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.persistence.repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import exforthia.embercrypt.persistence.entities.VaultPassword;

/**
 * Spring Data JPA repository for entity "VaultPassword" <br> 
 * 
 * This repository extends JpaRepository interface <br>
 * so it provides by default all the basic CRUD operations : <br>
 *   findById, findAll, save, delete, etc <br> 
 * with pagination and sorting : <br>
 *   findAll(Pageable), findAll(Sort)<br>
 * 
 * This repository can be extended by adding specific "finders" methods<br>
 * To do so, see the "predicates conventions" for "derived query methods" in Spring Data documentation
 * 
 * @author Telosys
 *
 */
@Repository
public interface VaultPasswordRepository extends JpaRepository<VaultPassword, Long> {

	// Insert specific finders here 

	//List<VaultPassword> findByXxx(String xxx);

	//List<VaultPassword> findByXxxStartingWith(String xxx);

	//List<VaultPassword> findByXxxContaining(String xxx);

	//List<VaultPassword> findByYyy(BigDecimal yyy);

	//List<VaultPassword> findByXxxContainingAndYyy(String xxx, BigDecimal yyy);
}
