/*
 * Created on 2025-09-29 ( 11:35:55 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package exforthia.embercrypt.persistence.entities;

import java.io.Serializable;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "VaultOtp"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name = "vault_otp", catalog = "exforthia_embercrypt_db")
@AllArgsConstructor
@NoArgsConstructor
public class VaultOtp implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_otp", nullable = false)
    private long idOtp;

    // --- OTHER DATA FIELDS
    @Column(name = "vault_ref", nullable = false, length = 36)
    private String vaultRef;

    @Column(name = "type", nullable = false, length = 4)
    private String type;

    @Column(name = "label", length = 200)
    private String label;

    @Column(name = "issuer_id")
    private Long issuerId;

    @Lob
    @Column(name = "secret_encrypted", nullable = false)
    private byte[] secretEncrypted;

    @Column(name = "algorithm", length = 20)
    private String algorithm;

    @Column(name = "digits")
    private Integer digits;

    @Column(name = "period")
    private Integer period;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Override
    public String toString() {
        String separator = "|";
        StringBuilder sb = new StringBuilder();
        sb.append("VaultOtp[");
        sb.append("idOtp=").append(idOtp);
        sb.append(separator).append("vaultRef=").append(vaultRef);
        sb.append(separator).append("type=").append(type);
        sb.append(separator).append("label=").append(label);
        sb.append(separator).append("issuerId=").append(issuerId);
        // attribute 'secretEncrypted' (type byte[]) not usable in toString()
        sb.append(separator).append("algorithm=").append(algorithm);
        sb.append(separator).append("digits=").append(digits);
        sb.append(separator).append("period=").append(period);
        sb.append(separator).append("createdAt=").append(createdAt);
        sb.append("]");
        return sb.toString();
    }

}
