/*
 * Created on 2025-09-29 ( 11:35:56 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.1.0
 */
package exforthia.embercrypt.persistence.entities;

import java.io.Serializable;
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Lob;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "VaultPassword"
 *
 * @author Telosys
 *
 */
@Data
@Entity
@Table(name="vault_password", catalog="exforthia_embercrypt_db" )
@AllArgsConstructor
@NoArgsConstructor
public class VaultPassword implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id_password", nullable=false)
    private long       idPassword ;

    //--- OTHER DATA FIELDS 
    @Column(name="vault_ref", nullable=false, length=36)
    private String     vaultRef ;

    @Lob
    @Column(name="encrypted_value", nullable=false)
    private byte[]     encryptedValue ;

    @Column(name="created_at")
    private LocalDateTime createdAt ;
    
    public void setIdPassword( long idPassword ) {
        this.idPassword = idPassword ;
    }
    public long getIdPassword() {
        return this.idPassword;
    }

    public void setVaultRef( String vaultRef ) {
        this.vaultRef = vaultRef ;
    }
    public String getVaultRef() {
        return this.vaultRef;
    }

    public void setEncryptedValue( byte[] encryptedValue ) {
        this.encryptedValue = encryptedValue ;
    }
    public byte[] getEncryptedValue() {
        return this.encryptedValue;
    }

    public void setCreatedAt( LocalDateTime createdAt ) {
        this.createdAt = createdAt ;
    }
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

	@Override
	public String toString() { 
		String separator = "|";
		StringBuilder sb = new StringBuilder();
		sb.append("VaultPassword[");
		sb.append("idPassword=").append(idPassword);
		sb.append(separator).append("vaultRef=").append(vaultRef);
		// attribute 'encryptedValue' (type byte[]) not usable in toString() 
		sb.append(separator).append("createdAt=").append(createdAt);
		sb.append("]");
		return sb.toString();
	}

}
