/*
 * Created on 2025-10-13 ( 13:34:59 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.persistence.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import jakarta.persistence.*;

import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "VaultPassword"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="vault_password", catalog="exforthia_embercrypt_db" )
public class VaultPassword implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id_password", nullable=false)
    private long       idPassword ;

    //--- OTHER DATA FIELDS 
    @Column(name="vault_ref", nullable=false, length=36)
    private String     vaultRef ;

    @Lob
    @Column(name="encrypted_value", nullable=false)
    private byte[]     encryptedValue ;

    @Column(name="created_at")
    private LocalDateTime createdAt ;

}