/*
 * Created on 2025-10-14 ( 08:56:31 )
 * Generated by Telosys ( https://www.telosys.org/ ) version 4.2.0
 */
package exforthia.embercrypt.persistence.entities;

import java.io.Serializable;
import java.time.LocalDateTime;
import jakarta.persistence.*;

import lombok.Data;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "VaultOtp"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="vault_otp", catalog="exforthia_embercrypt_db" )
public class VaultOtp implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id_otp", nullable=false)
    private long       idOtp ;

    //--- OTHER DATA FIELDS 
    @Column(name="vault_ref", nullable=false, length=36)
    private String     vaultRef ;

    @Column(name="type", nullable=false, length=4)
    private String     type ;

    @Column(name="label", length=200)
    private String     label ;

    @Column(name="issuer_id")
    private Long       issuerId ;

    @Lob
    @Column(name="secret_encrypted", nullable=false)
    private byte[]     secretEncrypted ;

    @Column(name="algorithm", length=20)
    private String     algorithm ;

    @Column(name="digits")
    private Integer    digits ;

    @Column(name="period")
    private Integer    period ;

    @Column(name="created_at")
    private LocalDateTime createdAt ;

}